project:
  type: website
  output-dir: _site

website:
  title: "My Movie Diary"
  site-url: https://<your-github-username>.github.io/<repo-name>/
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts/

format:
  html:
    theme:
      dark: solar
      light: cosmo
    css: styles.css
    grid:
      margin-width: 200px
