project:
  type: website
  output-dir: docs

website:
  title: "On Films"
  site-url: https://bhargav-dave.github.io/on-films/
  navbar:
    left:
      - text: Home
        href: index.qmd


format:
  html:
    theme:
      dark: cyborg
      light: materia
    css: styles.css
    grid:
      margin-width: 200px
